### ISSUE TITLE
Garbage collection bug 

### ISSUE THREAD

**Issue by beeldr** [24hoursmedia-craftcms/poll#28]
When running craft Garbage cleanup gc/run the process hangs on your plugin, could you take a look at that?

https://github.com/craftcms/cms/issues/7356

**Comment by 24HOURSMEDIA** [comment]
Hi, I'm sorry, I cannot really reproduce it (Craft Solo 3.6.4.1).

Apparently, the entry to be cleaned does not 'have a section or an invalid section',
and it does not appear to be in the plugin itself, but as you stated, appears to be similar like https://github.com/craftcms/cms/issues/5820.

More technical, the part of code causing the error is:
```
if ($element->section->handle) {
}
```

It results in 'Invalid section ID: 20' which indicates that the section for the entry could not be found (which should not even be possible as an Entry [which $element is] requires a section).

**Comment by 24hoursmedia-craftcms** [comment]
Hi, I'm sorry, I cannot really reproduce it (Craft Solo 3.6.4.1).

Apparently, the entry to be cleaned does not 'have a section or an invalid section',
and it does not appear to be in the plugin itself, but as you stated, appears to be similar like https://github.com/craftcms/cms/issues/5820.

More technical, the part of code causing the error is:
```
if ($element->section->handle) {
}
```

It results in 'Invalid section ID: 20' which indicates that the section for the entry could not be found (which should not even be possible as an Entry [which $element is] requires a section).

**Comment by 24HOURSMEDIA** [comment]
Plugin version v1.6.3 may fix this by ignoring the error.

Note:
- Since I could not reproduce the error, this has not been tested at all
- The fix may leave some 'poll answers' out of the garbage collection
- I still feel the real error is somewhere else, either in Craft or in data integrity. (because deducting from the logs, it appears a 'section' could not be found for an entry, which should always be the case).

**Comment by 24hoursmedia-craftcms** [comment]
Plugin version v1.6.3 may fix this by ignoring the error.

Note:
- Since I could not reproduce the error, this has not been tested at all
- The fix may leave some 'poll answers' out of the garbage collection
- I still feel the real error is somewhere else, either in Craft or in data integrity. (because deducting from the logs, it appears a 'section' could not be found for an entry, which should always be the case).
