### ISSUE TITLE
View results?

### ISSUE THREAD

**Issue by moondawg69** [24hoursmedia-craftcms/poll#9]
Couldn't see anything in the docs about viewing the results?

Who answered what, what they answered. Can you view say, 28 people said yes to Question 4?

Polls are only as useful as the reports into the results so people can action them.

That's why people use the common 3rd party tools. Reporting.

Is that on the roadmap?

**Comment by 24hoursmedia-craftcms** [comment]
Hi Jez,

How to view the number of votes per answer is in the docs on https://io.24hoursmedia.com/craftcms-poll/publish-polls

Certainly it’s a good idea to extend the poll with more detailed results (grouped by date, what polls has a user participated in).

For now the focus will be on ‘summarizing’ results, i.e. deleting the entries after closing a poll and generating a static report out of it.
Generating more detailed result reports for a poll will certainly be a part of that.

Regards

Van: Jez Timms <notifications@github.com>
Beantwoorden - Aan: 24hoursmedia-craftcms/poll <reply@reply.github.com>
Datum: woensdag 29 januari 2020 om 18:38
Aan: 24hoursmedia-craftcms/poll <poll@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [24hoursmedia-craftcms/poll] View results? (#9)


Couldn't see anything in the docs about viewing the results?

Who answered what, what they answered. Can you view say, 28 people said yes to Question 4?

Polls are only as useful as the reports into the results so people can action them.

That's why people use the common 3rd party tools. Reporting.

Is that on the roadmap?

**Comment by moondawg69** [comment]
Thanks for the reply :)

Sorry, I should of been clearer. The results to be viewed in the CP admin, not via front end templates as per the docs.

Reason being, then you could use the native export to csv, xml, json in the CP if you wished - as well as the front end.

That way, for now, people could crunch data in Excel for instance if they wished or used in a segment for email marketing or follow up polls. 

You would also have a central resource to view all the polls you have conducted, via the CP.

Cheers :)

**Comment by 24hoursmedia-craftcms** [comment]
Poll CSV/raw data download added in v1.1.2
https://io.24hoursmedia.com/craftcms-poll/csv-download-poll-votes

Thanks for the suggestion
